### ISSUE TITLE
Performance metrics

### ISSUE THREAD

**Issue by baudouindeparcevaux** [undpindia/Data4Policy#2]
Hello everyone,
Our group has 3 questions about how to determine if a farmer performs well or poorly. 

We can easily assume it is linked to the amount of the production. But since we want an intensive quantity, should the farmer also provide the **fields surface** ? So we could have a surfacic productivity (eg. in tonnes per km²). Is it also possible that some farmers plant more than once in a year ? (eg. hay) In that case, the system may require the **duration** dedicated to a specific crop (in order to compare two farmers that have produced the same amount but in different timelapses). And we would thus need a productivity in tonnes/(km².days).

Should the system take also into account the weather conditions or the soil humidity ? We think that someone in a sunny area should not be  put on an equal footing with someone in a cloudy one.

**Comment by parvathykrishnank** [comment]
Hello,

Since we are looking at the climate resilience of farmers, we can also look at factors other than productivity. Because getting farm-level productivity datasets is also of challenge. Some of the factors could be is some farms over time improving their cropping pattern, improve soil moisture, etc.
